// src/constants/galleryData.js (UPDATED for Clubs)

export const galleryCategories = [
  "Technical Clubs",
  "Cultural Clubs",
  "Robotics & Auto",
  "Startup & Entrepreneurship",
];

export const galleryImages = [
  {
    id: 1,
    src: "https://via.placeholder.com/600x400/0077C2/FFFFFF?text=GDGoC_Meetup",
    alt: "GDGoC members at a coding meetup",
    category: "Technical Clubs",
    title: "GDGoC: Annual Code-a-Thon",
    description: "The Google Developer Group On Campus hosted its annual hackathon, featuring cutting-edge projects and coding challenges.",
    tag: "Coding Event",
    date: "Nov 20, 2025",
  },
  {
    id: 2,
    src: "https://via.placeholder.com/600x400/B9383A/FFFFFF?text=E-Cell_Pitch",
    alt: "E-Cell members presenting startup pitches",
    category: "Startup & Entrepreneurship",
    title: "E-Cell: Startup Pitch Day",
    description: "The Entrepreneurship Cell hosted a pitching session for budding entrepreneurs, judged by industry veterans.",
    tag: "Pitching Event",
    date: "Oct 15, 2025",
  },
  {
    id: 3,
    src: "https://via.placeholder.com/600x400/2F2F2F/FFFFFF?text=Goonj_Performance",
    alt: "Goonj band performing on stage",
    category: "Cultural Clubs",
    title: "Goonj: Live Band Performance",
    description: "The college's official music band, Goonj, captivated the audience with a thrilling live performance during the cultural night.",
    tag: "Music & Arts",
    date: "Dec 5, 2025",
  },
  {
    id: 4,
    src: "https://via.placeholder.com/600x400/0077C2/FFFFFF?text=Robotics_Workshop",
    alt: "Robotronics club members assembling a robot",
    category: "Robotics & Auto",
    title: "Robotronics: Autonomous Vehicle Workshop",
    description: "A hands-on session where students learned to build and program small autonomous robots for competition.",
    tag: "Workshop",
    date: "Sep 10, 2025",
  },
  {
    id: 5,
    src: "https://via.placeholder.com/600x400/B9383A/FFFFFF?text=Coding_Comp",
    alt: "Students competing in a coding event",
    category: "Technical Clubs",
    title: "Binary Blitz: Competitive Coding",
    description: "An intensive coding competition organized by the Technical Council to test algorithmic skills.",
    tag: "Competition",
    date: "Aug 28, 2025",
  },
  {
    id: 6,
    src: "https://via.placeholder.com/600x400/2F2F2F/FFFFFF?text=NSS_Drive",
    alt: "NSS students participating in a cleanliness drive",
    category: "Cultural Clubs",
    title: "NSS: Community Service Drive",
    description: "Students volunteering for a local community clean-up and awareness campaign.",
    tag: "Social Initiative",
    date: "Jul 1, 2025",
  },
  {
    id: 7,
    src: "https://via.placeholder.com/600x400/0077C2/FFFFFF?text=Aero_Model",
    alt: "Aero club demonstrating a drone model",
    category: "Robotics & Auto",
    title: "Aero Club: Drone Modeling Display",
    description: "Showcasing advanced drone models and flight control systems developed by the aerospace enthusiasts.",
    tag: "Demonstration",
    date: "Jan 12, 2026",
  },
  {
    id: 8,
    src: "https://via.placeholder.com/600x400/B9383A/FFFFFF?text=Entrepreneur_Talk",
    alt: "Guest speaker at an E-Cell session",
    category: "Startup & Entrepreneurship",
    title: "E-Cell: Guest Lecture Series",
    description: "An inspiring talk by a successful alumnus entrepreneur on scaling a tech startup.",
    tag: "Guest Talk",
    date: "Feb 5, 2026",
  },
];